app = "part11-ci-cd"

[build]

[env]
  PORT = "5000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
