name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: Set commit messages
        id: commit_messages
        run: echo "messages<<EOF" >> $GITHUB_OUTPUT && echo "${{ toJson(github.event.commits.*.message) }}" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Print commit messages
        if: ${{ !contains(join(github.event.commits.*.message, ' '), 'skip') }}
        run: echo "${{ steps.commit_messages.outputs.messages }}"